version: '3'

services:
  web:
    build: ./
    entrypoint: 
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
  # app:
  #   build: 
  #     context: ./
    ports:
      - "5000:5000"
    # command: python3 app.py 
    image: cfchem:latest
    volumes:
      - .:/cfchem