services:
  cfchemapps:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - static:/cfchemapps/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static:/cfchemapps/static
    ports:
      - "80:80"
    depends_on:
      - cfchemapps

volumes:
  static: