version: '3.8'

services:
  app:
    build:
      context: ./
    ports:
    - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    image: cfchem:latest
    volumes:
      - .:/cfchem
    env_file:
      - ./.env.dev