# version: '3.8'

# services:
#   web:
#     build:
#       context: ./
#       dockerfile: Dockerfile.prod
#     # command: gunicorn cfchem.wsgi:application --bind 0.0.0.0:5000
#     ports:
#       - 5000:5000
#     env_file:
#       - ./.env.prod
#     depends_on:
#       - db
#   db:
#     image: postgres
#     volumes:
#       - cfchem-db:/var/lib/postgresql/data/
#     env_file:
#       - ./.env.prod.db

# volumes:
#   cfchem-db:

version: '3.8'

services:
  cfchemapps:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      # - static_vol:/cfchemapps/static
      - media_vol:/cfchemapps/media
      # - css_vol:/cfchemapps/static/css
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      # - static_vol:/cfchemapps/static
      - media_vol:/cfchemapps/media
      # - css_vol:/cfchemapps/static/css
    ports:
      - "80:80"
    depends_on:
      - cfchemapps

volumes:
  # static_vol:
  media_vol:
  # css_vol: